/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LabelField: typeof import('./src/components/LabelField.vue')['default']
    LabelRequired: typeof import('./src/components/LabelRequired.vue')['default']
    Manifest: typeof import('./src/components/Manifest.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBar: typeof import('./src/components/StatusBar.vue')['default']
    Tooltip: typeof import('./src/components/Tooltip.vue')['default']
    WasteInfo: typeof import('./src/components/WasteInfo.vue')['default']
  }
}
